apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodeport }}  # Correct indentation
  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
